# Generated by Django 4.0.4 on 2022-04-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moteur', models.CharField(max_length=30)),
                ('carburant', models.FloatField()),
                ('marque', models.CharField(max_length=30)),
                ('cv', models.FloatField()),
                ('year', models.FloatField()),
                ('voiture', models.CharField(max_length=30)),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
